### ISSUE TITLE
Installing react-with-styles-interface-css package throws warning

### ISSUE THREAD

**Issue by ramyashanmugasundaram** [airbnb/react-with-styles-interface-css#18]
> While installing react-with-styles-interface-css package throws the below warning. I am using version 4.0.1

**npm WARN deprecated array.prototype.flatten@1.2.1: This method has been renamed to "flat" - please use `array.prototype.flat` instead**

It would be great if you consume **array.prototype.flat** package, instead of array.prototype.flatten and release a patch or version.

**Comment by ljharb** [comment]
Deprecation messages aren't "thrown", they're usually-ignorable console logs during install.

We certainly can update the package here, but it's not actually causing any issues.

**Comment by ljharb** [comment]
v4.0.2 published.

**Comment by ramyashanmugasundaram** [comment]
Great. Thanks for the quick update
